finos/legend-integration-juju

LOCAL_RUN.md
``snap alias microk8s.kubectl kubectl`` requires sudo.
``sudo usermod -a -G microk8s $USER`` is required in order to run ``newgrp microk8s`` with the current user and without ``sudo``.
There is no ``profile`` file, but there is a ``.profile`` file.
``microk8s install`` is an invalid command.
``microk8s enable dns,storage,ingress`` is invalid, they should be separated by spaces, not commas.
=> Corrects some of the steps listed in the README file

INSTRUCTIONS/AWS EKS/README.md
The gitlab Callback URIs have to be updated as well after TLS was enabled.
=> Amend some details on the EKS deployment (TLS)

INSTRUCTIONS/AWS EKS/README.md
There are a few back and forths in the EKS deployment guide, which can make it harder to follow. This will move the hostname and TLS configuration before the gitlab application creation, so there's no back and forth between these sections, making it easier to follow.
Splits the TLS configuration section in 2. Moves the "own certificates" section in the second part.
Move the "/etc/hosts" and Amazon Load Balancer connection methods to the Appendix.
=> Restructure the EKS deployment guide

INSTRUCTIONS/AWS EKS/README.md
By default, Cloudflare sets the SSL/TLS configuration option to Flexible, which means that it will terminate the TLS and send the
request further as HTTP, which would then be redicted to HTTPS by the NGINX Ingress, which would basically result in an infinite redirect.
=> Adds a note regarding Proxy TLS termination

.github/workflows/scheduled.yaml, docs/periodic_job.md
The job will run periodically, and will refresh the Legend Engine, Studio, and SDLC charms to their latest revisions for a configured Juju EKS deployment of FINOS Legend.
In order for the job to run properly, the following secrets need to be added: ``KUBECONFIG_B64``, ``CONTROLLERS_B64``, ``CONTROLLER_PASSWORD``.
Adds documentation about the job, including information about the secrets mentioned above.
=> Adds periodic Juju refresh on Public Legend Instance

.github/workflows/scheduled.yaml
Running juju status will show us the charm revision numbers. This will be useful to check if the revision numbers get updated afterwards.
=> actions: Adds juju status before refreshing the charms

.github/workflows/scheduled.yaml
A fix for this issue has been merged and released under juju 2.9.28.
Reference: https://bugs.launchpad.net/juju/+bug/1965902
=> Removes the || true from juju refresh

docs/deploy/aws-eks.md
When using a proxying service such as Cloudflare, we need to make sure that the proxy service will not perform the TLS termination. If it does, the NGINX Ingress Controller will receive a HTTP request instead, and will redirect to HTTPS, which will result in an infinite redirect.
=> EKS: Adds information about HTTPS redirection

.github/workflows/scheduled.yaml
The action was meant to refresh the Legend deployment periodically.
=> Reenables the juju refresh cron job

.github/workflows/renew_certificate.yaml, docs/deploy/aws-eks.md
Starting with juju v3.0.0, juju run should be used of juju run-action. [1]
[1] https://juju.is/docs/olm/manage-actions#heading--run-an-action
=> actions: Updates juju run-action to juju run

.github/workflows/scheduled.yaml
By using `channel=3.0/stable` we pin the `juju` installation to version 3.0.x. This increases the deployment stability.
=> Pin `juju` to `v3.0.x` when refreshing deployment

.github/workflows/renew_certificate.yaml, .github/workflows/scheduled.yaml
The FINOS Legend instance has been migrated to a Juju v3.0.2 controller.
=> Switches Public Instance controller to the newer one

.github/workflows/renew_certificate.yaml, .github/workflows/scheduled.yaml
The FINOS Legend instance has been migrated to a Juju v3.0.2 controller.
=> Switches Public Instance controller to the newer one (login)

.github/workflows/renew_certificate.yaml, .github/workflows/scheduled.yaml, docs/periodic_job.md
If one of the periodic jobs fails, an email is sent. The email is only sent if the workflow action is triggered by the cron job.
=> Send email on failure of periodic workflow actions

.github/workflows/renew_certificate.yaml
``juju run`` doesn't include a status anymore. We can check the exit code instead.
=> Updates action success check

docs/deploy/aws-eks.md, docs/deploy/local.md
The deployment guide is not properly configured for Juju version 3.1/stable. I have updated the documentation to work for 3.1 stable versions as well as modifying the microk8s installer based on the guide from [get-started-with-juju](https://juju.is/docs/juju/get-started-with-juju).
=> Update Legend deployment documentation

.github/workflows/switch_env.yaml
We currently have 2 Juju FINOS Legend models in the EKS deployment, finos-legend and finos-legend-twin, one of which will be considered the Production environment and the other one as the Staging environment. The plan is to keep the Staging environment up-to-date with the latest Legend releases, and switch the environments monthly.
Adds a dispatchable GitHub action that will switch these 2 environments.
=> Adds EKS deployment Legend Prod and Staging switch Github Action

.github/workflows/switch_env.yaml
After switching the Legend environment staging and Prod environments, disable the Refresh EKS FINOS Legend deployment, so we have the ability to switch back if something went wrong with the new Prod environment. Otherwise, the daily action would refresh the staging environment to the latest version.
The disabled action will have to be enabled manually afterwards.
=> actions: Disable Refresh EKS Legend deployment on switch

.github/workflows/scheduled.yaml
Increases the timeout for waiting for Legend to become available from 300 seconds to 400 seconds.
Switches the order of the components we check to the same order in which they're refreshed.
=> actions: Updates the Refresh EKS Legend deployment action

.github/workflows/scheduled.yaml
We've added an ingress "/" route for Legend docs to the staging model, which means that https://staging.legend.finos.org/ no longer returns a 302 Found HTTP code, but 200 OK instead.
Updates the "Refresh EKS FINOS Legend deployment" action to check for 200 OK for https://staging.legend.finos.org/
=> actions: Updates the scheduled refresh action check

.github/workflows/renew_certificate.yaml
``set -e`` tells the script to exit the script if any command returns a non-zero exit status.
``set -x`` is useful for debugging, essentially allowing us to trace the script execution.
=> jobs: Adds set -e and set -x flags to the renew_certificate job
